# Generated by Django 5.0.4 on 2024-04-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_alter_driver_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='password',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='password',
        ),
    ]
