# Generated by Django 5.0.4 on 2024-04-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_remove_driver_password_remove_parent_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='language',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='language',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='bus_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='company',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license',
            field=models.TextField(null=True),
        ),
    ]
