# Generated by Django 5.0.4 on 2024-05-02 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_driver_created_at_driver_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('parent_id', models.UUIDField()),
                ('date', models.DateTimeField()),
                ('status', models.TextField()),
                ('admin_id', models.UUIDField(null=True)),
                ('address', models.TextField(null=True)),
                ('template_id', models.UUIDField(null=True)),
                ('email', models.TextField(null=True)),
                ('zip_postal', models.TextField(null=True)),
                ('note', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Request',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('image', models.TextField()),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Template',
            },
        ),
    ]
