# Generated by Django 5.0.4 on 2024-05-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_request_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='date',
        ),
    ]
