# Generated by Django 5.0.4 on 2024-05-06 04:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_remove_request_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('parent_id', models.UUIDField()),
                ('child_name', models.TextField()),
                ('nickname', models.TextField()),
                ('gender', models.TextField()),
                ('date_of_birth', models.DateTimeField(null=True)),
                ('card_number', models.TextField(null=True)),
                ('avatar', models.TextField(null=True)),
                ('name', models.TextField()),
                ('address', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Child',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.TextField(null=True),
        ),
    ]
