# Generated by Django 5.0.4 on 2024-05-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='device',
            field=models.TextField(null=True),
        ),
    ]
