# Generated by Django 5.0.4 on 2024-05-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_parent_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='type',
            field=models.TextField(null=True),
        ),
    ]
