# Generated by Django 5.0.4 on 2024-05-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_history_location_history_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='school',
            field=models.TextField(null=True),
        ),
    ]
