# Generated by Django 5.0.4 on 2024-05-09 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_child_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='address',
        ),
    ]
