# Generated by Django 5.0.4 on 2024-05-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_remove_child_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='phone_number',
            field=models.TextField(null=True),
        ),
    ]
