# Generated by Django 5.0.4 on 2024-05-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_request_name_request_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='shipping_by',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='shipping_code',
            field=models.TextField(null=True),
        ),
    ]
