# Generated by Django 5.0.4 on 2024-05-09 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_request_shipping_by_request_shipping_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=255)),
                ('name_cn', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.RemoveField(
            model_name='child',
            name='school',
        ),
        migrations.AddField(
            model_name='child',
            name='school_id',
            field=models.UUIDField(null=True),
        ),
    ]
