# Generated by Django 5.0.4 on 2024-05-09 09:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0016_school_delete_history_remove_child_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('driver_id', models.UUIDField()),
                ('child_id', models.UUIDField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.TextField(null=True)),
                ('type', models.TextField(null=True)),
            ],
            options={
                'db_table': 'History',
            },
        ),
    ]
