# Generated by Django 5.0.4 on 2024-05-09 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0017_history'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='school',
            table='School',
        ),
    ]
