# Generated by Django 5.0.4 on 2024-05-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0018_alter_school_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
