# Generated by Django 5.0.4 on 2024-05-16 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0022_alter_driver_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('subtitle', models.TextField(null=True)),
                ('body', models.TextField()),
                ('parent_id', models.UUIDField()),
            ],
        ),
    ]
