# Generated by Django 5.0.4 on 2024-05-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0023_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='notification',
            table='Notification',
        ),
    ]
