# Generated by Django 5.0.4 on 2024-06-11 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0025_userkey'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userkey',
            table='UserKey',
        ),
    ]
